export const airports = [
  { city: "Bengaluru", code: "BLR", name: "Kempegowda International" },
  { city: "Chennai", code: "MAA", name: "Chennai International" },
  { city: "Kochi", code: "COK", name: "Cochin International" },
  { city: "Kolkata", code: "CCU", name: "Netaji Subhas Chandra Bose International" },
  { city: "Hyderabad", code: "HYD", name: "Rajiv Gandhi International" },
  { city: "Ahmedabad", code: "AMD", name: "Sardar Vallabhbhai Patel International" },
  { city: "Dubai", code: "DXB", name: "Dubai International" },
  { city: "Doha", code: "DOH", name: "Hamad International" },
  { city: "Bangkok", code: "BKK", name: "Suvarnabhumi" },
  { city: "Rome", code: "FCO", name: "Leonardo da Vinci–Fiumicino" },
  { city: "Istanbul", code: "IST", name: "Istanbul Airport" },
  { city: "London", code: "LHR", name: "Heathrow" },
  { city: "New York", code: "JFK", name: "John F. Kennedy International" },
  { city: "Paris", code: "CDG", name: "Charles de Gaulle" },
  { city: "Tokyo", code: "HND", name: "Haneda" },
  { city: "Singapore", code: "SIN", name: "Changi" },
  { city: "Delhi", code: "DEL", name: "Indira Gandhi International" },
  { city: "Mumbai", code: "BOM", name: "Chhatrapati Shivaji Maharaj International" },
];

export const flightOptions = [
  {
    id: "LF-401",
    airline: "Luma Air",
    airlineCode: "LA",
    origin: "Bengaluru (BLR)",
    destination: "Dubai (DXB)",
    departureTime: "06:20",
    arrivalTime: "09:10",
    durationMinutes: 260,
    returnDepartureTime: "11:30",
    returnArrivalTime: "17:00",
    returnDurationMinutes: 230,
    returnStops: 0,
    stops: 0,
    price: 228,
    baggage: "7 kg cabin + 20 kg checked",
    fare: "Flex Economy",
    amenities: ["Seat selection", "Changes permitted", "Meal included"],
    bestScore: 1,
    aircraft: "Airbus A321neo",
  },
  {
    id: "LF-402",
    airline: "Gulf Horizon",
    airlineCode: "GH",
    origin: "Bengaluru (BLR)",
    destination: "Dubai (DXB)",
    departureTime: "09:45",
    arrivalTime: "12:40",
    durationMinutes: 265,
    returnDepartureTime: "14:10",
    returnArrivalTime: "19:40",
    returnDurationMinutes: 240,
    returnStops: 0,
    stops: 0,
    price: 196,
    baggage: "7 kg cabin + 15 kg checked",
    fare: "Saver Economy",
    amenities: ["Standard seat", "Meal included"],
    bestScore: 2,
    aircraft: "Boeing 737 MAX 8",
  },
  {
    id: "LF-403",
    airline: "Skybridge Airways",
    airlineCode: "SA",
    origin: "Bengaluru (BLR)",
    destination: "Dubai (DXB)",
    departureTime: "14:10",
    arrivalTime: "18:35",
    durationMinutes: 295,
    returnDepartureTime: "13:20",
    returnArrivalTime: "19:15",
    returnDurationMinutes: 355,
    returnStops: 1,
    returnStopCity: "Mumbai",
    stops: 1,
    stopCity: "Mumbai",
    price: 174,
    baggage: "7 kg cabin + 20 kg checked",
    fare: "Economy Standard",
    amenities: ["Seat selection", "Changes permitted"],
    bestScore: 3,
    aircraft: "Airbus A320",
  },
  {
    id: "LF-404",
    airline: "Luma Air",
    airlineCode: "LA",
    origin: "Bengaluru (BLR)",
    destination: "Dubai (DXB)",
    departureTime: "21:30",
    arrivalTime: "00:20",
    durationMinutes: 260,
    returnDepartureTime: "06:50",
    returnArrivalTime: "12:20",
    returnDurationMinutes: 240,
    returnStops: 0,
    stops: 0,
    price: 248,
    baggage: "7 kg cabin + 25 kg checked",
    fare: "Comfort Economy",
    amenities: ["Extra legroom", "Seat selection", "Meal included"],
    bestScore: 4,
    aircraft: "Airbus A321neo",
  },
  {
    id: "LF-405",
    airline: "Northstar Airlines",
    airlineCode: "NA",
    origin: "New York (JFK)",
    destination: "Paris (CDG)",
    departureTime: "18:15",
    arrivalTime: "07:20",
    durationMinutes: 425,
    returnDepartureTime: "10:30",
    returnArrivalTime: "13:15",
    returnDurationMinutes: 525,
    returnStops: 0,
    stops: 0,
    price: 462,
    baggage: "8 kg cabin + 23 kg checked",
    fare: "Economy Classic",
    amenities: ["Seat selection", "Dinner included", "USB charging"],
    bestScore: 1,
    aircraft: "Boeing 787-9",
  },
  {
    id: "LF-406",
    airline: "EuroVista",
    airlineCode: "EV",
    origin: "New York (JFK)",
    destination: "Paris (CDG)",
    departureTime: "16:40",
    arrivalTime: "07:55",
    durationMinutes: 435,
    returnDepartureTime: "11:15",
    returnArrivalTime: "14:05",
    returnDurationMinutes: 530,
    returnStops: 0,
    stops: 0,
    price: 398,
    baggage: "8 kg cabin + 20 kg checked",
    fare: "Economy Light",
    amenities: ["Complimentary snack", "USB charging"],
    bestScore: 2,
    aircraft: "Airbus A350-900",
  },
  {
    id: "LF-407",
    airline: "Crescent Airways",
    airlineCode: "CA",
    origin: "London (LHR)",
    destination: "Tokyo (HND)",
    departureTime: "10:05",
    arrivalTime: "07:25",
    durationMinutes: 800,
    returnDepartureTime: "11:20",
    returnArrivalTime: "17:10",
    returnDurationMinutes: 890,
    returnStops: 0,
    stops: 0,
    price: 738,
    baggage: "8 kg cabin + 23 kg checked",
    fare: "Economy Flex",
    amenities: ["Seat selection", "Meal included", "Changes permitted"],
    bestScore: 1,
    aircraft: "Boeing 787-10",
  },
  {
    id: "LF-408",
    airline: "Luma Air",
    airlineCode: "LA",
    origin: "London (LHR)",
    destination: "Tokyo (HND)",
    departureTime: "13:30",
    arrivalTime: "12:10",
    durationMinutes: 820,
    returnDepartureTime: "14:40",
    returnArrivalTime: "20:45",
    returnDurationMinutes: 905,
    returnStops: 1,
    returnStopCity: "Doha",
    stops: 1,
    stopCity: "Doha",
    price: 612,
    baggage: "7 kg cabin + 23 kg checked",
    fare: "Economy Standard",
    amenities: ["Meal included", "USB charging"],
    bestScore: 2,
    aircraft: "Airbus A350-900",
  },
  {
    id: "LF-409",
    airline: "Pacific Link",
    airlineCode: "PL",
    origin: "Singapore (SIN)",
    destination: "Tokyo (HND)",
    departureTime: "08:25",
    arrivalTime: "16:20",
    durationMinutes: 415,
    returnDepartureTime: "18:00",
    returnArrivalTime: "00:10",
    returnDurationMinutes: 370,
    returnStops: 0,
    stops: 0,
    price: 318,
    baggage: "7 kg cabin + 20 kg checked",
    fare: "Economy Saver",
    amenities: ["Snack included", "USB charging"],
    bestScore: 1,
    aircraft: "Airbus A330-300",
  },
  {
    id: "LF-410",
    airline: "Crescent Airways",
    airlineCode: "CA",
    origin: "Singapore (SIN)",
    destination: "Tokyo (HND)",
    departureTime: "22:10",
    arrivalTime: "06:05",
    durationMinutes: 415,
    returnDepartureTime: "08:00",
    returnArrivalTime: "14:10",
    returnDurationMinutes: 370,
    returnStops: 0,
    stops: 0,
    price: 354,
    baggage: "8 kg cabin + 25 kg checked",
    fare: "Economy Flex",
    amenities: ["Seat selection", "Meal included"],
    bestScore: 2,
    aircraft: "Boeing 787-8",
  },
  {
    id: "LF-411",
    airline: "Deccan Connect",
    airlineCode: "DC",
    origin: "Delhi (DEL)",
    destination: "London (LHR)",
    departureTime: "02:15",
    arrivalTime: "07:05",
    durationMinutes: 560,
    returnDepartureTime: "12:30",
    returnArrivalTime: "01:15",
    returnDurationMinutes: 585,
    returnStops: 0,
    stops: 0,
    price: 486,
    baggage: "7 kg cabin + 25 kg checked",
    fare: "Economy Value",
    amenities: ["Meal included", "USB charging"],
    bestScore: 1,
    aircraft: "Boeing 787-9",
  },
  {
    id: "LF-412",
    airline: "EuroVista",
    airlineCode: "EV",
    origin: "Mumbai (BOM)",
    destination: "Paris (CDG)",
    departureTime: "01:40",
    arrivalTime: "07:35",
    durationMinutes: 565,
    returnDepartureTime: "11:20",
    returnArrivalTime: "20:55",
    returnDurationMinutes: 605,
    returnStops: 0,
    stops: 0,
    price: 512,
    baggage: "8 kg cabin + 23 kg checked",
    fare: "Economy Classic",
    amenities: ["Seat selection", "Meal included"],
    bestScore: 1,
    aircraft: "Airbus A350-900",
  },
  {
    id: "LF-413",
    airline: "Deccan Connect",
    airlineCode: "DC",
    origin: "Hyderabad (HYD)",
    destination: "Dubai (DXB)",
    departureTime: "06:10",
    arrivalTime: "08:35",
    durationMinutes: 175,
    returnDepartureTime: "10:20",
    returnArrivalTime: "15:55",
    returnDurationMinutes: 215,
    returnStops: 0,
    stops: 0,
    price: 214,
    baggage: "7 kg cabin + 20 kg checked",
    fare: "Economy Value",
    amenities: ["Meal included", "USB charging"],
    bestScore: 1,
    aircraft: "Airbus A320neo",
  },
  {
    id: "LF-414",
    airline: "Pacific Link",
    airlineCode: "PL",
    origin: "Chennai (MAA)",
    destination: "Singapore (SIN)",
    departureTime: "09:20",
    arrivalTime: "16:10",
    durationMinutes: 320,
    returnDepartureTime: "18:25",
    returnArrivalTime: "20:00",
    returnDurationMinutes: 265,
    returnStops: 0,
    stops: 0,
    price: 186,
    baggage: "7 kg cabin + 20 kg checked",
    fare: "Economy Saver",
    amenities: ["Snack included", "USB charging"],
    bestScore: 1,
    aircraft: "Airbus A321",
  },
  {
    id: "LF-415",
    airline: "Crescent Airways",
    airlineCode: "CA",
    origin: "Kochi (COK)",
    destination: "Doha (DOH)",
    departureTime: "04:35",
    arrivalTime: "07:05",
    durationMinutes: 180,
    returnDepartureTime: "09:40",
    returnArrivalTime: "16:20",
    returnDurationMinutes: 220,
    returnStops: 0,
    stops: 0,
    price: 205,
    baggage: "8 kg cabin + 25 kg checked",
    fare: "Economy Flex",
    amenities: ["Seat selection", "Meal included"],
    bestScore: 1,
    aircraft: "Boeing 787-8",
  },
  {
    id: "LF-416",
    airline: "Skybridge Airways",
    airlineCode: "SA",
    origin: "Kolkata (CCU)",
    destination: "Bangkok (BKK)",
    departureTime: "11:10",
    arrivalTime: "15:05",
    durationMinutes: 145,
    returnDepartureTime: "17:20",
    returnArrivalTime: "18:40",
    returnDurationMinutes: 140,
    returnStops: 0,
    stops: 0,
    price: 162,
    baggage: "7 kg cabin + 15 kg checked",
    fare: "Economy Standard",
    amenities: ["Standard seat", "Snack included"],
    bestScore: 1,
    aircraft: "Airbus A320",
  },
  {
    id: "LF-417",
    airline: "EuroVista",
    airlineCode: "EV",
    origin: "Ahmedabad (AMD)",
    destination: "Rome (FCO)",
    departureTime: "02:40",
    arrivalTime: "11:20",
    durationMinutes: 640,
    returnDepartureTime: "13:10",
    returnArrivalTime: "00:55",
    returnDurationMinutes: 625,
    returnStops: 0,
    stops: 1,
    stopCity: "Istanbul",
    price: 428,
    baggage: "8 kg cabin + 23 kg checked",
    fare: "Economy Classic",
    amenities: ["Seat selection", "Meal included"],
    bestScore: 1,
    aircraft: "Airbus A330-300",
  },
];

export function formatDuration(minutes) {
  const hours = Math.floor(minutes / 60);
  const remainingMinutes = minutes % 60;
  return `${hours}h ${remainingMinutes.toString().padStart(2, "0")}m`;
}

export function formatTripDate(date) {
  if (!date) return "Date not selected";
  return new Intl.DateTimeFormat("en-US", {
    weekday: "short",
    month: "short",
    day: "numeric",
    year: "numeric",
  }).format(new Date(`${date}T12:00:00`));
}
